/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.wbydo.reading_generative_art

import processing.core.*

class Processing : PApplet () {
    override fun settings() : Unit {
        size(400, 300)
    }
    override fun setup() : Unit {
        background(0.0f)
    }

    override fun draw() : Unit {
        fill(255)
        noStroke()
        ellipse(mouseX.toFloat(), mouseY.toFloat(), 10.0f, 10.0f)
    }

    fun run(args: Array<String>) : Unit
            = PApplet.main("com.wbydo.reading_generative_art.Processing")
}

fun main(args : Array<String>) : Unit = Processing().run(args)
