/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.wbydo.reading_generative_art

import processing.core.*

class Processing : PApplet () {
    override fun settings() : Unit {
        size(800, 600)
        smooth()
    }
    override fun setup() : Unit {
        background(255f)
        strokeWeight(1f)

        val r0 = 0f
        val x0 = (width / 2).toFloat()
        val y0 = (height / 2).toFloat()

        stroke(20f, 50f, 70f)
        noFill()

        var prevX = x0
        var prevY = y0
        var prevR = r0
        for (theta in 0..(360 * 20) step 1) {
            val rad = radians(theta.toFloat())
            val r = prevR
            val x = x0 + r * cos(rad)
            val y = y0 + r * sin(rad)
            line(prevX, prevY, x, y)

            prevR += (random(1f) - 0.5f) * 10
            prevX = x
            prevY = y
        }

        saveFrame("tmp.jpg")
    }

    override fun draw() : Unit {
    }

    fun run(args: Array<String>) : Unit
            = PApplet.main("com.wbydo.reading_generative_art.Processing")
}

fun main(args : Array<String>) : Unit = Processing().run(args)
